# Generated by Django 6.1 on 2026-08-31 13:54

import gestion.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collaborateur',
            managers=[
                ('objects', gestion.models.CollaborateurManager()),
            ],
        ),
    ]
