# Generated by Django 6.1 on 2026-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_collaborateur_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
    ]
